# Generated by Django 2.2.2 on 2019-06-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'verbose_name': 'Detalle de Factura', 'verbose_name_plural': 'Detalles de Factura'},
        ),
    ]
